#!/usr/bin/env python3
from pathlib import Path
import json,re,sys

ROOT=Path(__file__).resolve().parents[1]
VERSION=int((ROOT/'VERSION').read_text(encoding='utf-8').strip())
index=(ROOT/'index.html').read_text(encoding='utf-8')

# Keep manifest + version metadata aligned with the current release.
version_path=ROOT/'version.json'
version=json.loads(version_path.read_text(encoding='utf-8'))
version['appVersion']=VERSION
version_path.write_text(json.dumps(version,indent=2)+"\n",encoding='utf-8')

manifest_path=ROOT/'manifest.json'
manifest=json.loads(manifest_path.read_text(encoding='utf-8'))
manifest['id']='./'
manifest['start_url']='./'
manifest['scope']='./'
manifest['display']='standalone'
manifest.pop('display_override',None)
manifest['prefer_related_applications']=False
manifest['icons']=[
    {'src':'./assets/icons/mediaflow-install-192.png','sizes':'192x192','type':'image/png','purpose':'any'},
    {'src':'./assets/icons/mediaflow-install-512.png','sizes':'512x512','type':'image/png','purpose':'any'},
    {'src':'./assets/icons/mediaflow-maskable-512.png','sizes':'512x512','type':'image/png','purpose':'maskable'}
]
manifest_path.write_text(json.dumps(manifest,indent=2)+"\n",encoding='utf-8')

# Discover local app-shell assets from index.html so future MediaFlow releases do
# not need a hand-maintained service-worker list.
assets=[]
for href in re.findall(r'<link[^>]+href=["\']([^"\']+)["\'][^>]*>',index,re.I):
    if href.startswith(('http://','https://','//','data:')):
        continue
    if href.endswith('.css') or 'manifest' in href or 'icon' in href:
        assets.append('./'+href.lstrip('./'))
for src in re.findall(r'<script[^>]+src=["\']([^"\']+)["\'][^>]*>',index,re.I):
    if src.startswith(('http://','https://','//','data:')):
        continue
    assets.append('./'+src.lstrip('./'))

fixed=[
    './','./index.html','./manifest.json','./version.json','./sw.js',
    './assets/icons/mediaflow-192.png','./assets/icons/mediaflow-512.png',
    './assets/icons/mediaflow-install-192.png','./assets/icons/mediaflow-install-512.png',
    './assets/icons/mediaflow-maskable-512.png','./assets/icons/apple-touch-icon.png',
    './favicon.ico','./assets/icons/mediaflow.ico','./assets/icons/favicon-32.png'
]
category_icons=['./'+p.relative_to(ROOT).as_posix() for p in sorted((ROOT/'assets/category-icons').glob('*.png'))]
assets=fixed+category_icons+assets
seen=set()
assets=[x for x in assets if not (x in seen or seen.add(x))]

missing=[]
for rel in assets:
    if rel in ('./','./sw.js'):
        continue
    p=ROOT/rel[2:]
    if not p.exists():
        missing.append(rel)
if missing:
    print('PWA generation failed; missing app-shell assets:',*missing,sep='\n- ')
    sys.exit(1)

assets_js='\n'.join(f'  {json.dumps(x)},' for x in assets).rstrip(',')
cache=f'mediaflow-pwa-v{VERSION}-shell-v1'

# v247+ intentionally does not use cache.addAll(APP_SHELL). A single transient
# 404 used to reject the whole install event. Each asset is now cached
# independently; failed files are visible through GET_DIAGNOSTICS and can be
# retried through RETRY_APP_SHELL_CACHE without killing worker installation.
sw_template=r'''/* MediaFlow __VERSION_LABEL__ Progressive Web App service worker.
   Generated by scripts/pwa.py — do not hand-maintain the asset list. */
const MEDIAFLOW_VERSION=__VERSION_NUM__;
const CACHE_PREFIX='mediaflow-pwa-';
const SHELL_CACHE=__CACHE_JSON__;
const APP_SHELL=[
__ASSETS_JS__
];
const APP_SCOPE_URL=new URL('./',self.registration.scope);
const APP_INDEX_URL=new URL('./index.html',self.registration.scope);
const VERSION_URL=new URL('./version.json',self.registration.scope);
const MANIFEST_URL=new URL('./manifest.json',self.registration.scope);
const WORKER_URL=new URL('./sw.js',self.registration.scope);

function scopedRequest(url,cacheMode='reload'){
  const absolute=new URL(url,self.registration.scope);
  return new Request(absolute,{cache:cacheMode,credentials:'same-origin'});
}

async function cacheOne(cache,url){
  try{
    const request=scopedRequest(url,'reload');
    const response=await fetch(request);
    if(!response||!response.ok)throw new Error(`HTTP ${response?.status||0}`);
    await cache.put(request,response.clone());
    return {url,ok:true,status:response.status};
  }catch(err){
    return {url,ok:false,status:0,error:String(err?.message||err||'cache failed')};
  }
}

async function cacheShellAssets(urls=APP_SHELL){
  const cache=await caches.open(SHELL_CACHE);
  const results=await Promise.allSettled(urls.map(url=>cacheOne(cache,url)));
  const normalized=results.map((row,i)=>row.status==='fulfilled'
    ? row.value
    : {url:urls[i],ok:false,status:0,error:String(row.reason||'cache failed')});
  return {
    ok:normalized.every(x=>x.ok),
    cached:normalized.filter(x=>x.ok).map(x=>x.url),
    failed:normalized.filter(x=>!x.ok)
  };
}

async function shellDiagnostics(){
  const cache=await caches.open(SHELL_CACHE);
  const missingCached=[];
  let cachedCount=0;
  for(const url of APP_SHELL){
    try{
      const hit=await cache.match(scopedRequest(url,'default'));
      if(hit)cachedCount++;
      else missingCached.push(url);
    }catch(_){
      missingCached.push(url);
    }
  }
  return {
    type:'MEDIAFLOW_SW_DIAGNOSTICS',
    version:MEDIAFLOW_VERSION,
    cacheName:SHELL_CACHE,
    shellCount:APP_SHELL.length,
    cachedCount,
    missingCached,
    appShell:[...APP_SHELL]
  };
}

function replyMessage(event,payload){
  try{
    if(event.ports&&event.ports[0])event.ports[0].postMessage(payload);
    else event.source?.postMessage(payload);
  }catch(_){ }
}

self.addEventListener('install',event=>{
  event.waitUntil((async()=>{
    try{
      // Fault tolerant: one missing/temporary asset must never reject the whole
      // service-worker installation. Diagnostics/repair exposes any misses.
      await cacheShellAssets(APP_SHELL);
    }catch(err){
      console.warn('[MediaFlow PWA] app-shell pre-cache was incomplete',err);
    }
  })());
});

self.addEventListener('activate',event=>{
  event.waitUntil((async()=>{
    const keys=await caches.keys();
    await Promise.all(
      keys
        .filter(key=>(key.startsWith(CACHE_PREFIX)||key.startsWith('mediaflow-v'))&&key!==SHELL_CACHE)
        .map(key=>caches.delete(key))
    );

    // Retry transient misses once on activation, while still allowing the
    // worker to activate even if one optional asset remains unavailable.
    try{
      const diag=await shellDiagnostics();
      if(diag.missingCached.length)await cacheShellAssets(diag.missingCached);
    }catch(_){ }

    await self.clients.claim();
    const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});
    clients.forEach(client=>client.postMessage({type:'MEDIAFLOW_SW_ACTIVATED',version:MEDIAFLOW_VERSION}));
  })());
});

self.addEventListener('message',event=>{
  const type=event.data?.type;

  if(type==='SKIP_WAITING'){
    self.skipWaiting();
    return;
  }

  if(type==='GET_VERSION'){
    replyMessage(event,{type:'MEDIAFLOW_SW_VERSION',version:MEDIAFLOW_VERSION});
    return;
  }

  if(type==='GET_DIAGNOSTICS'){
    event.waitUntil((async()=>{
      try{
        replyMessage(event,await shellDiagnostics());
      }catch(err){
        replyMessage(event,{
          type:'MEDIAFLOW_SW_DIAGNOSTICS',
          version:MEDIAFLOW_VERSION,
          error:String(err?.message||err)
        });
      }
    })());
    return;
  }

  if(type==='RETRY_APP_SHELL_CACHE'){
    event.waitUntil((async()=>{
      try{
        const before=await shellDiagnostics();
        const retried=await cacheShellAssets(before.missingCached.length?before.missingCached:APP_SHELL);
        const after=await shellDiagnostics();
        replyMessage(event,{
          ...after,
          type:'MEDIAFLOW_SW_CACHE_RESULT',
          version:MEDIAFLOW_VERSION,
          retried
        });
      }catch(err){
        replyMessage(event,{
          type:'MEDIAFLOW_SW_CACHE_RESULT',
          version:MEDIAFLOW_VERSION,
          error:String(err?.message||err)
        });
      }
    })());
  }
});

function isAppDocument(url){
  return url.origin===APP_SCOPE_URL.origin&&
    (url.pathname===APP_SCOPE_URL.pathname||url.pathname===APP_INDEX_URL.pathname);
}

async function networkFirst(request,fallbackUrl){
  const cache=await caches.open(SHELL_CACHE);
  try{
    const response=await fetch(request);
    if(response&&response.ok)eventualPut(cache,request,response.clone());
    return response;
  }catch(err){
    const cached=await cache.match(request);
    if(cached)return cached;
    if(fallbackUrl){
      const fallback=await cache.match(scopedRequest(fallbackUrl,'default'));
      if(fallback)return fallback;
    }
    throw err;
  }
}

function eventualPut(cache,request,response){
  Promise.resolve(cache.put(request,response)).catch(()=>{});
}

async function cacheFirst(request){
  const cache=await caches.open(SHELL_CACHE);
  const cached=await cache.match(request);
  if(cached)return cached;
  const response=await fetch(request);
  if(response&&response.ok)eventualPut(cache,request,response.clone());
  return response;
}

self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.method!=='GET')return;
  const url=new URL(request.url);
  if(url.origin!==self.location.origin)return;

  if(request.mode==='navigate'||isAppDocument(url)){
    event.respondWith(networkFirst(request,'./index.html'));
    return;
  }

  if(url.pathname===VERSION_URL.pathname||url.pathname===MANIFEST_URL.pathname||url.pathname===WORKER_URL.pathname){
    event.respondWith(networkFirst(request));
    return;
  }

  const scopePath=APP_SCOPE_URL.pathname;
  const relative='./'+url.pathname.slice(scopePath.length);
  if(APP_SHELL.includes(relative)){
    event.respondWith(cacheFirst(request));
  }
});
'''

sw=(sw_template
    .replace('__VERSION_LABEL__',f'v{VERSION}')
    .replace('__VERSION_NUM__',str(VERSION))
    .replace('__CACHE_JSON__',json.dumps(cache))
    .replace('__ASSETS_JS__',assets_js))
(ROOT/'sw.js').write_text(sw,encoding='utf-8')
print(f'PWA synced for v{VERSION}: {len(assets)} local app-shell assets -> {cache}')
