; NSIS Installer Script
; Generated by ExeForge HTML to Windows EXE Builder

!define PRODUCT_NAME "MediaFlow"
!define PRODUCT_VERSION "13.0.0"
!define PRODUCT_PUBLISHER "Alex Godly"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\MediaFlow.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\MediaFlow"

SetCompressor lzma

!include "MUI2.nsh"

Name "MediaFlow ${PRODUCT_VERSION}"
OutFile "dist\MediaFlow-Setup-${PRODUCT_VERSION}.exe"
InstallDir "$PROGRAMFILES\MediaFlow"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File /r "dist\win-unpacked\*"
  CreateDirectory "$SMPROGRAMS\MediaFlow"
  CreateShortCut "$SMPROGRAMS\MediaFlow\MediaFlow.lnk" "$INSTDIR\MediaFlow.exe"
  CreateShortCut "$DESKTOP\MediaFlow.lnk" "$INSTDIR\MediaFlow.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\MediaFlow.exe"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayName" "MediaFlow"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "Publisher" "Alex Godly"
SectionEnd

Section Uninstall
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\MediaFlow\MediaFlow.lnk"
  RMDir "$SMPROGRAMS\MediaFlow"
  Delete "$DESKTOP\MediaFlow.lnk"
  DeleteRegKey HKLM "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
SectionEnd
