/* MediaFlow v244 Progressive Web App service worker.
   Generated by scripts/pwa.py — do not hand-maintain the asset list. */
const MEDIAFLOW_VERSION=244;
const CACHE_PREFIX='mediaflow-pwa-';
const SHELL_CACHE="mediaflow-pwa-v244-shell-v1";
const APP_SHELL=[
  "./",
  "./index.html",
  "./manifest.json",
  "./version.json",
  "./assets/icons/mediaflow-192.png",
  "./assets/icons/mediaflow-512.png",
  "./assets/icons/mediaflow-maskable-512.png",
  "./assets/icons/apple-touch-icon.png",
  "./assets/css/00-foundation.css",
  "./assets/css/10-navigation-core-ui.css",
  "./assets/css/20-dashboard-personal-order.css",
  "./assets/css/30-categories-themes-navigation.css",
  "./assets/css/40-system-import-tools.css",
  "./assets/css/50-library-dashboard.css",
  "./assets/css/60-statistics.css",
  "./assets/css/70-full-style-themes.css",
  "./assets/css/80-late-control-center.css",
  "./assets/css/92-v221-settings-polish.css",
  "./assets/css/93-v222-dashboard-rendering-stability.css",
  "./assets/css/94-v224-library-sorting-actions.css",
  "./assets/css/95-v225-icons-personal-order.css",
  "./assets/css/96-v226-semantic-ui-library.css",
  "./assets/css/97-v227-ui-icon-corrections.css",
  "./assets/css/98-v228-library-priority-dynamic-row.css",
  "./assets/css/99-v229-library-choice-modals.css",
  "./assets/css/100-v230-choice-filter-layout.css",
  "./assets/css/101-v231-settings-layout-inheritance.css",
  "./assets/css/102-v232-performance-details-settings.css",
  "./assets/css/103-v233-dynamic-settings-title-details-cover.css",
  "./assets/css/104-v234-dashboard-quick-inputs.css",
  "./assets/css/105-v235-missing-cover-live-validation.css",
  "./assets/css/106-v236-searchable-category-filter.css",
  "./assets/css/107-v237-cross-surface-category-filters.css",
  "./assets/css/108-v238-status-logging-responsive-device-mode.css",
  "./assets/css/109-v239-batch-log-editor-responsive-cleanup.css",
  "./assets/css/110-v240-edit-title-cover-profile.css",
  "./assets/css/111-v241-editor-history-performance.css",
  "./assets/css/112-v242-logging-history-performance.css",
  "./assets/css/113-v243-logging-cover-batch-filter.css",
  "./assets/css/114-v244-pwa.css",
  "./assets/js/mediaflow-v244.bundle.js"
];
const APP_SCOPE_URL=new URL('./',self.registration.scope);
const APP_INDEX_URL=new URL('./index.html',self.registration.scope);
const VERSION_URL=new URL('./version.json',self.registration.scope);
const MANIFEST_URL=new URL('./manifest.json',self.registration.scope);

self.addEventListener('install',event=>{
  event.waitUntil((async()=>{
    const cache=await caches.open(SHELL_CACHE);
    await cache.addAll(APP_SHELL.map(url=>new Request(url,{cache:'reload'})));
  })());
});

self.addEventListener('activate',event=>{
  event.waitUntil((async()=>{
    const keys=await caches.keys();
    await Promise.all(keys.filter(key=>(key.startsWith(CACHE_PREFIX)||key.startsWith('mediaflow-v'))&&key!==SHELL_CACHE).map(key=>caches.delete(key)));
    await self.clients.claim();
    const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});
    clients.forEach(client=>client.postMessage({type:'MEDIAFLOW_SW_ACTIVATED',version:MEDIAFLOW_VERSION}));
  })());
});

self.addEventListener('message',event=>{
  if(event.data?.type==='SKIP_WAITING')self.skipWaiting();
  if(event.data?.type==='GET_VERSION')event.source?.postMessage({type:'MEDIAFLOW_SW_VERSION',version:MEDIAFLOW_VERSION});
});

function isAppDocument(url){
  return url.origin===APP_SCOPE_URL.origin&&(url.pathname===APP_SCOPE_URL.pathname||url.pathname===APP_INDEX_URL.pathname);
}

async function networkFirst(request,fallbackUrl){
  const cache=await caches.open(SHELL_CACHE);
  try{
    const response=await fetch(request);
    if(response&&response.ok)eventualPut(cache,request,response.clone());
    return response;
  }catch(err){
    return (await cache.match(request))||(fallbackUrl?await cache.match(fallbackUrl):null)||Promise.reject(err);
  }
}

function eventualPut(cache,request,response){
  Promise.resolve(cache.put(request,response)).catch(()=>{});
}

async function cacheFirst(request){
  const cache=await caches.open(SHELL_CACHE);
  const cached=await cache.match(request);
  if(cached)return cached;
  const response=await fetch(request);
  if(response&&response.ok)eventualPut(cache,request,response.clone());
  return response;
}

self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.method!=='GET')return;
  const url=new URL(request.url);
  if(url.origin!==self.location.origin)return;

  if(request.mode==='navigate'||isAppDocument(url)){
    event.respondWith(networkFirst(request,'./index.html'));
    return;
  }

  if(url.pathname===VERSION_URL.pathname||url.pathname===MANIFEST_URL.pathname){
    event.respondWith(networkFirst(request));
    return;
  }

  const scopePath=APP_SCOPE_URL.pathname;
  const relative='./'+url.pathname.slice(scopePath.length);
  if(APP_SHELL.includes(relative)){
    event.respondWith(cacheFirst(request));
  }
});
