#!/usr/bin/env python3
from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[1]
VERSION=int((ROOT/'VERSION').read_text(encoding='utf-8').strip())
index=(ROOT/'index.html').read_text(encoding='utf-8')

# Keep manifest + version metadata aligned with the current release.
version_path=ROOT/'version.json'
version=json.loads(version_path.read_text(encoding='utf-8'))
version['appVersion']=VERSION
version_path.write_text(json.dumps(version,indent=2)+"\n",encoding='utf-8')

manifest_path=ROOT/'manifest.json'
manifest=json.loads(manifest_path.read_text(encoding='utf-8'))
manifest.setdefault('id','./')
manifest['start_url']='./'
manifest['scope']='./'
manifest['display']='standalone'
manifest_path.write_text(json.dumps(manifest,indent=2)+"\n",encoding='utf-8')

# Discover local app-shell assets from index.html so future MediaFlow releases do
# not need a hand-maintained service-worker list.
assets=[]
for href in re.findall(r'<link[^>]+href=["\']([^"\']+)["\'][^>]*>',index,re.I):
    if href.startswith(('http://','https://','//','data:')): continue
    if href.endswith('.css') or 'manifest' in href or 'icon' in href:
        assets.append('./'+href.lstrip('./'))
for src in re.findall(r'<script[^>]+src=["\']([^"\']+)["\'][^>]*>',index,re.I):
    if src.startswith(('http://','https://','//','data:')): continue
    assets.append('./'+src.lstrip('./'))
fixed=[
    './','./index.html','./manifest.json','./version.json',
    './assets/icons/mediaflow-192.png','./assets/icons/mediaflow-512.png',
    './assets/icons/mediaflow-maskable-512.png','./assets/icons/apple-touch-icon.png'
]
assets=fixed+assets
# dedupe while retaining order
seen=set(); assets=[x for x in assets if not (x in seen or seen.add(x))]
missing=[]
for rel in assets:
    if rel=='./': continue
    p=ROOT/rel[2:]
    if not p.exists(): missing.append(rel)
if missing:
    print('PWA generation failed; missing app-shell assets:',*missing,sep='\n- ')
    sys.exit(1)

assets_js='\n'.join(f'  {json.dumps(x)},' for x in assets).rstrip(',')
cache=f'mediaflow-pwa-v{VERSION}-shell-v1'
sw=f'''/* MediaFlow v{VERSION} Progressive Web App service worker.\n   Generated by scripts/pwa.py — do not hand-maintain the asset list. */\nconst MEDIAFLOW_VERSION={VERSION};\nconst CACHE_PREFIX='mediaflow-pwa-';\nconst SHELL_CACHE={json.dumps(cache)};\nconst APP_SHELL=[\n{assets_js}\n];\nconst APP_SCOPE_URL=new URL('./',self.registration.scope);\nconst APP_INDEX_URL=new URL('./index.html',self.registration.scope);\nconst VERSION_URL=new URL('./version.json',self.registration.scope);\nconst MANIFEST_URL=new URL('./manifest.json',self.registration.scope);\n\nself.addEventListener('install',event=>{{\n  event.waitUntil((async()=>{{\n    const cache=await caches.open(SHELL_CACHE);\n    await cache.addAll(APP_SHELL.map(url=>new Request(url,{{cache:'reload'}})));\n  }})());\n}});\n\nself.addEventListener('activate',event=>{{\n  event.waitUntil((async()=>{{\n    const keys=await caches.keys();\n    await Promise.all(keys.filter(key=>(key.startsWith(CACHE_PREFIX)||key.startsWith('mediaflow-v'))&&key!==SHELL_CACHE).map(key=>caches.delete(key)));\n    await self.clients.claim();\n    const clients=await self.clients.matchAll({{type:'window',includeUncontrolled:true}});\n    clients.forEach(client=>client.postMessage({{type:'MEDIAFLOW_SW_ACTIVATED',version:MEDIAFLOW_VERSION}}));\n  }})());\n}});\n\nself.addEventListener('message',event=>{{\n  if(event.data?.type==='SKIP_WAITING')self.skipWaiting();\n  if(event.data?.type==='GET_VERSION')event.source?.postMessage({{type:'MEDIAFLOW_SW_VERSION',version:MEDIAFLOW_VERSION}});\n}});\n\nfunction isAppDocument(url){{\n  return url.origin===APP_SCOPE_URL.origin&&(url.pathname===APP_SCOPE_URL.pathname||url.pathname===APP_INDEX_URL.pathname);\n}}\n\nasync function networkFirst(request,fallbackUrl){{\n  const cache=await caches.open(SHELL_CACHE);\n  try{{\n    const response=await fetch(request);\n    if(response&&response.ok)eventualPut(cache,request,response.clone());\n    return response;\n  }}catch(err){{\n    return (await cache.match(request))||(fallbackUrl?await cache.match(fallbackUrl):null)||Promise.reject(err);\n  }}\n}}\n\nfunction eventualPut(cache,request,response){{\n  Promise.resolve(cache.put(request,response)).catch(()=>{{}});\n}}\n\nasync function cacheFirst(request){{\n  const cache=await caches.open(SHELL_CACHE);\n  const cached=await cache.match(request);\n  if(cached)return cached;\n  const response=await fetch(request);\n  if(response&&response.ok)eventualPut(cache,request,response.clone());\n  return response;\n}}\n\nself.addEventListener('fetch',event=>{{\n  const request=event.request;\n  if(request.method!=='GET')return;\n  const url=new URL(request.url);\n  if(url.origin!==self.location.origin)return;\n\n  if(request.mode==='navigate'||isAppDocument(url)){{\n    event.respondWith(networkFirst(request,'./index.html'));\n    return;\n  }}\n\n  if(url.pathname===VERSION_URL.pathname||url.pathname===MANIFEST_URL.pathname){{\n    event.respondWith(networkFirst(request));\n    return;\n  }}\n\n  const scopePath=APP_SCOPE_URL.pathname;\n  const relative='./'+url.pathname.slice(scopePath.length);\n  if(APP_SHELL.includes(relative)){{\n    event.respondWith(cacheFirst(request));\n  }}\n}});\n'''
(ROOT/'sw.js').write_text(sw,encoding='utf-8')
print(f'PWA synced for v{VERSION}: {len(assets)} local app-shell assets -> {cache}')
