/* MediaFlow v358 Progressive Web App service worker.
   Generated by scripts/pwa.py — do not hand-maintain the asset list. */
const MEDIAFLOW_VERSION=358;
const CACHE_PREFIX='mediaflow-pwa-';
const SHELL_CACHE="mediaflow-pwa-v358-shell-v1";
const APP_SHELL=[
  "./",
  "./index.html",
  "./manifest.json",
  "./version.json",
  "./sw.js",
  "./assets/icons/mediaflow-192.png",
  "./assets/icons/mediaflow-512.png",
  "./assets/icons/mediaflow-install-192.png",
  "./assets/icons/mediaflow-install-512.png",
  "./assets/icons/mediaflow-maskable-512.png",
  "./assets/icons/apple-touch-icon.png",
  "./favicon.ico",
  "./assets/icons/mediaflow.ico",
  "./assets/icons/favicon-32.png",
  "./assets/category-icons/anime-backlog.png",
  "./assets/category-icons/anime-movies-backlog.png",
  "./assets/category-icons/anime-movies.png",
  "./assets/category-icons/asian-comics-backlog.png",
  "./assets/category-icons/asian-comics.png",
  "./assets/category-icons/books-backlog.png",
  "./assets/category-icons/books.png",
  "./assets/category-icons/comics-backlog.png",
  "./assets/category-icons/comics.png",
  "./assets/category-icons/finished-anime.png",
  "./assets/category-icons/magazines-backlog.png",
  "./assets/category-icons/magazines.png",
  "./assets/category-icons/missed-anime.png",
  "./assets/category-icons/movies-backlog.png",
  "./assets/category-icons/movies.png",
  "./assets/category-icons/novels-backlog.png",
  "./assets/category-icons/novels.png",
  "./assets/category-icons/online-media-backlog.png",
  "./assets/category-icons/online-media.png",
  "./assets/category-icons/seasonal-anime.png",
  "./assets/category-icons/tv-series-backlog.png",
  "./assets/category-icons/tv-series.png",
  "./assets/css/00-foundation.css",
  "./assets/css/10-navigation-core-ui.css",
  "./assets/css/20-dashboard-personal-order.css",
  "./assets/css/30-categories-themes-navigation.css",
  "./assets/css/40-system-import-tools.css",
  "./assets/css/50-library-dashboard.css",
  "./assets/css/167-v340-history-navigation-recent-titles.css",
  "./assets/css/168-v341-history-tab-pagination-performance.css",
  "./assets/css/169-v342-recent-view-ui-polish.css",
  "./assets/css/170-v343-recent-view-spacing-daypart-icons.css",
  "./assets/css/171-v344-recent-view-remove-title-and-daypart-icons.css",
  "./assets/css/172-v345-personal-order-list-tab-queues.css",
  "./assets/css/173-v346-queue-tab-icons-controls.css",
  "./assets/css/174-v348-universal-streak-action-xp.css",
  "./assets/css/175-v348-xp-history.css",
  "./assets/css/60-statistics.css",
  "./assets/css/155-v295-responsive-default-categories.css",
  "./assets/css/156-v296-category-recovery-responsive-more.css",
  "./assets/css/157-v297-auth-refresh.css",
  "./assets/css/70-full-style-themes.css",
  "./assets/css/80-late-control-center.css",
  "./assets/css/92-v221-settings-polish.css",
  "./assets/css/93-v222-dashboard-rendering-stability.css",
  "./assets/css/94-v224-library-sorting-actions.css",
  "./assets/css/95-v225-icons-personal-order.css",
  "./assets/css/96-v226-semantic-ui-library.css",
  "./assets/css/97-v227-ui-icon-corrections.css",
  "./assets/css/98-v228-library-priority-dynamic-row.css",
  "./assets/css/99-v229-library-choice-modals.css",
  "./assets/css/100-v230-choice-filter-layout.css",
  "./assets/css/101-v231-settings-layout-inheritance.css",
  "./assets/css/102-v232-performance-details-settings.css",
  "./assets/css/103-v233-dynamic-settings-title-details-cover.css",
  "./assets/css/104-v234-dashboard-quick-inputs.css",
  "./assets/css/105-v235-missing-cover-live-validation.css",
  "./assets/css/106-v236-searchable-category-filter.css",
  "./assets/css/107-v237-cross-surface-category-filters.css",
  "./assets/css/108-v238-status-logging-responsive-device-mode.css",
  "./assets/css/109-v239-batch-log-editor-responsive-cleanup.css",
  "./assets/css/110-v240-edit-title-cover-profile.css",
  "./assets/css/111-v241-editor-history-performance.css",
  "./assets/css/112-v242-logging-history-performance.css",
  "./assets/css/113-v243-logging-cover-batch-filter.css",
  "./assets/css/114-v244-pwa.css",
  "./assets/css/115-v246-pwa-mobile-responsive.css",
  "./assets/css/116-v247-pwa-reliability-diagnostics.css",
  "./assets/css/117-v248-settings-update-install.css",
  "./assets/css/118-v250-about-updates-data-integrity.css",
  "./assets/css/119-v252-seasons-view.css",
  "./assets/css/120-v253-seasons-history-logging-polish.css",
  "./assets/css/121-v254-library-cover-overlays.css",
  "./assets/css/122-v255-cover-status-colors.css",
  "./assets/css/123-v256-cover-sizing-runtime-calculator.css",
  "./assets/css/124-v257-dashboard-cloud-settings-mobile-pwa-update-backup.css",
  "./assets/css/125-v258-category-editor-icons-persistence-audit.css",
  "./assets/css/126-v259-category-icon-showcase-polish.css",
  "./assets/css/127-v260-react-redesign.css",
  "./assets/css/128-v261-library-history-balance-polish.css",
  "./assets/css/129-v262-library-restore.css",
  "./assets/css/130-v264-library-balance-order-settings-polish.css",
  "./assets/css/131-v265-ux-stability-sidebar-balance.css",
  "./assets/css/132-v266-title-library-settings-nav-fixes.css",
  "./assets/css/133-v267-sync-order-balance-dynamic-cover-reliability.css",
  "./assets/css/134-v269-consumption-history-redesign.css",
  "./assets/css/135-v270-performance-version-cleanup.css",
  "./assets/css/136-v271-history-ui-polish.css",
  "./assets/css/137-v272-logs-covers-edit-title-fix.css",
  "./assets/css/138-v273-drag-responsive-app.css",
  "./assets/css/139-v274-collections-library-order.css",
  "./assets/css/140-v275-order-edge-resize-collection-add.css",
  "./assets/css/141-v276-collections-personal-order-polish.css",
  "./assets/css/142-v277-navigation-breakpoint-fix.css",
  "./assets/css/143-v278-responsive-bottom-nav-visual-parity.css",
  "./assets/css/144-v279-collections-progress-background-performance.css",
  "./assets/css/145-v280-collection-cover-progress-selection-hero.css",
  "./assets/css/146-v281-collection-compact-card-search-sync.css",
  "./assets/css/147-v282-category-collections-stability.css",
  "./assets/css/148-v283-category-modal-sidebar-collection-card-fixes.css",
  "./assets/css/149-v284-account-compact-progress-fix.css",
  "./assets/css/150-v287-personal-order-collection-queues.css",
  "./assets/css/151-v288-personal-order-queue-views.css",
  "./assets/css/152-v289-personal-order-editor-choice-parity.css",
  "./assets/css/153-v290-category-selector-ui-visibility.css",
  "./assets/css/154-v291-searchable-category-picker.css",
  "./assets/css/158-v298-auth-layout-fix.css",
  "./assets/css/159-v301-current-rerolls-responsive.css",
  "./assets/css/160-v331-per-title-logging-timestamps.css",
  "./assets/css/161-v334-active-time-dashboard.css",
  "./assets/css/162-v335-stats-xp-calculator.css",
  "./assets/css/163-v336-dialogs-active-time-analytics.css",
  "./assets/css/164-v337-active-time-dual-milestones.css",
  "./assets/css/165-v338-normal-cover-selection.css",
  "./assets/css/176-v350-mobile-native-layout.css",
  "./assets/css/177-v351-mobile-regression-repairs.css",
  "./assets/css/178-v352-collection-add-picker-views.css",
  "./assets/css/179-v353-mobile-add-titles-tools.css",
  "./assets/css/180-v354-personal-order-quick-workspace.css",
  "./assets/css/181-v355-personal-order-ui-refinement.css",
  "./assets/css/182-v356-personal-order-dialog-browse-layout.css",
  "./assets/css/183-v357-personal-order-dialogs-tabs-icons.css",
  "./assets/css/184-v358-personal-order-rebuild.css",
  "./assets/js/mediaflow-v358.bundle.js",
  "./assets/js/mediaflow-v261-react-ui.js"
];
const APP_SCOPE_URL=new URL('./',self.registration.scope);
const APP_INDEX_URL=new URL('./index.html',self.registration.scope);
const VERSION_URL=new URL('./version.json',self.registration.scope);
const MANIFEST_URL=new URL('./manifest.json',self.registration.scope);
const WORKER_URL=new URL('./sw.js',self.registration.scope);

function scopedRequest(url,cacheMode='reload'){
  const absolute=new URL(url,self.registration.scope);
  return new Request(absolute,{cache:cacheMode,credentials:'same-origin'});
}

async function cacheOne(cache,url){
  try{
    const request=scopedRequest(url,'reload');
    const response=await fetch(request);
    if(!response||!response.ok)throw new Error(`HTTP ${response?.status||0}`);
    await cache.put(request,response.clone());
    return {url,ok:true,status:response.status};
  }catch(err){
    return {url,ok:false,status:0,error:String(err?.message||err||'cache failed')};
  }
}

async function cacheShellAssets(urls=APP_SHELL){
  const cache=await caches.open(SHELL_CACHE);
  const results=await Promise.allSettled(urls.map(url=>cacheOne(cache,url)));
  const normalized=results.map((row,i)=>row.status==='fulfilled'
    ? row.value
    : {url:urls[i],ok:false,status:0,error:String(row.reason||'cache failed')});
  return {
    ok:normalized.every(x=>x.ok),
    cached:normalized.filter(x=>x.ok).map(x=>x.url),
    failed:normalized.filter(x=>!x.ok)
  };
}

async function shellDiagnostics(){
  const cache=await caches.open(SHELL_CACHE);
  const missingCached=[];
  let cachedCount=0;
  for(const url of APP_SHELL){
    try{
      const hit=await cache.match(scopedRequest(url,'default'));
      if(hit)cachedCount++;
      else missingCached.push(url);
    }catch(_){
      missingCached.push(url);
    }
  }
  return {
    type:'MEDIAFLOW_SW_DIAGNOSTICS',
    version:MEDIAFLOW_VERSION,
    cacheName:SHELL_CACHE,
    shellCount:APP_SHELL.length,
    cachedCount,
    missingCached,
    appShell:[...APP_SHELL]
  };
}

function replyMessage(event,payload){
  try{
    if(event.ports&&event.ports[0])event.ports[0].postMessage(payload);
    else event.source?.postMessage(payload);
  }catch(_){ }
}

self.addEventListener('install',event=>{
  event.waitUntil((async()=>{
    try{
      // Fault tolerant: one missing/temporary asset must never reject the whole
      // service-worker installation. Diagnostics/repair exposes any misses.
      await cacheShellAssets(APP_SHELL);
    }catch(err){
      console.warn('[MediaFlow PWA] app-shell pre-cache was incomplete',err);
    }
  })());
});

self.addEventListener('activate',event=>{
  event.waitUntil((async()=>{
    const keys=await caches.keys();
    await Promise.all(
      keys
        .filter(key=>(key.startsWith(CACHE_PREFIX)||key.startsWith('mediaflow-v'))&&key!==SHELL_CACHE)
        .map(key=>caches.delete(key))
    );

    // Retry transient misses once on activation, while still allowing the
    // worker to activate even if one optional asset remains unavailable.
    try{
      const diag=await shellDiagnostics();
      if(diag.missingCached.length)await cacheShellAssets(diag.missingCached);
    }catch(_){ }

    await self.clients.claim();
    const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});
    clients.forEach(client=>client.postMessage({type:'MEDIAFLOW_SW_ACTIVATED',version:MEDIAFLOW_VERSION}));
  })());
});

self.addEventListener('message',event=>{
  const type=event.data?.type;

  if(type==='SKIP_WAITING'){
    self.skipWaiting();
    return;
  }

  if(type==='GET_VERSION'){
    replyMessage(event,{type:'MEDIAFLOW_SW_VERSION',version:MEDIAFLOW_VERSION});
    return;
  }

  if(type==='GET_DIAGNOSTICS'){
    event.waitUntil((async()=>{
      try{
        replyMessage(event,await shellDiagnostics());
      }catch(err){
        replyMessage(event,{
          type:'MEDIAFLOW_SW_DIAGNOSTICS',
          version:MEDIAFLOW_VERSION,
          error:String(err?.message||err)
        });
      }
    })());
    return;
  }

  if(type==='RETRY_APP_SHELL_CACHE'){
    event.waitUntil((async()=>{
      try{
        const before=await shellDiagnostics();
        const retried=await cacheShellAssets(before.missingCached.length?before.missingCached:APP_SHELL);
        const after=await shellDiagnostics();
        replyMessage(event,{
          ...after,
          type:'MEDIAFLOW_SW_CACHE_RESULT',
          version:MEDIAFLOW_VERSION,
          retried
        });
      }catch(err){
        replyMessage(event,{
          type:'MEDIAFLOW_SW_CACHE_RESULT',
          version:MEDIAFLOW_VERSION,
          error:String(err?.message||err)
        });
      }
    })());
  }
});

function isAppDocument(url){
  return url.origin===APP_SCOPE_URL.origin&&
    (url.pathname===APP_SCOPE_URL.pathname||url.pathname===APP_INDEX_URL.pathname);
}

async function networkFirst(request,fallbackUrl){
  const cache=await caches.open(SHELL_CACHE);
  try{
    const response=await fetch(request);
    if(response&&response.ok)eventualPut(cache,request,response.clone());
    return response;
  }catch(err){
    const cached=await cache.match(request);
    if(cached)return cached;
    if(fallbackUrl){
      const fallback=await cache.match(scopedRequest(fallbackUrl,'default'));
      if(fallback)return fallback;
    }
    throw err;
  }
}

function eventualPut(cache,request,response){
  Promise.resolve(cache.put(request,response)).catch(()=>{});
}

async function cacheFirst(request){
  const cache=await caches.open(SHELL_CACHE);
  const cached=await cache.match(request);
  if(cached)return cached;
  const response=await fetch(request);
  if(response&&response.ok)eventualPut(cache,request,response.clone());
  return response;
}

self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.method!=='GET')return;
  const url=new URL(request.url);
  if(url.origin!==self.location.origin)return;

  if(request.mode==='navigate'||isAppDocument(url)){
    event.respondWith(networkFirst(request,'./index.html'));
    return;
  }

  if(url.pathname===VERSION_URL.pathname||url.pathname===MANIFEST_URL.pathname||url.pathname===WORKER_URL.pathname){
    event.respondWith(networkFirst(request));
    return;
  }

  const scopePath=APP_SCOPE_URL.pathname;
  const relative='./'+url.pathname.slice(scopePath.length);
  if(APP_SHELL.includes(relative)){
    event.respondWith(cacheFirst(request));
  }
});
